#!/bin/bash
# leedevkit bootstrap — per-project install (no global)
# Usage: curl -fsSL https://raw.githubusercontent.com/vkaylee/leedevkit/main/bootstrap.sh | bash
#
# Downloads the devkit release and installs it into .leedevkit/ in the current
# directory. No global install, no PATH modification, no root permissions.

set -euo pipefail

REPO="vkaylee/leedevkit"
VERSION="${1:-latest}"

# Must be in a project directory (has .git or leedevkit.toml)
if [ ! -d .git ] && [ ! -f leedevkit.toml ]; then
    echo "⚠️  No .git or leedevkit.toml found in current directory."
    echo "   Run this from your project root, or create leedevkit.toml first."
    echo ""
    echo "   mkdir my-project && cd my-project"
    echo "   git init"
    echo "   curl -fsSL .../bootstrap.sh | bash"
    exit 1
fi

echo "🚀 Installing leedevkit into .leedevkit/ (per-project, no global)..."

# Determine version tag
if [ "$VERSION" = "latest" ]; then
    VERSION_TAG=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": "\(.*\)".*/\1/')
else
    VERSION_TAG="$VERSION"
fi

echo "   Version: $VERSION_TAG"

# Download release tarball
TMP_DIR=$(mktemp -d)
trap 'rm -rf $TMP_DIR' EXIT

# Strip "v" prefix for tarball name (v0.1.0 → leedevkit-0.1.0.tar.gz)
VER="${VERSION_TAG#v}"
TARBALL_URL="https://github.com/$REPO/releases/download/$VERSION_TAG/leedevkit-${VER}.tar.gz"
echo "   Downloading: $TARBALL_URL"

if command -v curl &>/dev/null; then
    curl -fsSL "$TARBALL_URL" -o "$TMP_DIR/leedevkit.tar.gz"
elif command -v wget &>/dev/null; then
    wget -q "$TARBALL_URL" -O "$TMP_DIR/leedevkit.tar.gz"
else
    echo "❌ Need curl or wget"
    exit 1
fi

# Extract into .leedevkit/ in current directory
rm -rf .leedevkit
tar -xzf "$TMP_DIR/leedevkit.tar.gz" -C "$TMP_DIR"
EXTRACTED=$(find "$TMP_DIR" -maxdepth 1 -type d -name 'leedevkit-*' | head -1)
if [ -z "$EXTRACTED" ]; then
    echo "❌ Unexpected tarball structure"
    exit 1
fi
mv "$EXTRACTED" .leedevkit

# Ensure scripts are executable
chmod +x .leedevkit/scripts/*.py 2>/dev/null || true
chmod +x .leedevkit/scripts/*.sh 2>/dev/null || true
chmod +x .leedevkit/bin/* 2>/dev/null || true

# Create project-local wrapper (real script, not symlink)
cat > leedevkit << 'WRAPPER'
#!/bin/bash
# LeeDevKit — project-local wrapper (auto-generated by bootstrap)
exec "$(cd "$(dirname "$0")" && pwd)/.leedevkit/bin/leedevkit" "$@"
WRAPPER
chmod +x leedevkit

# Create leedevkit.toml if missing
if [ ! -f leedevkit.toml ]; then
    PROJECT_NAME="$(basename "$(pwd)")"
    PROJECT_NAMESPACE="$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')"
    cat > leedevkit.toml << TOML
[devkit]
version = "$VERSION_TAG"
install = "per-project"
source = "release"

[project]
name = "$PROJECT_NAME"
namespace = "$PROJECT_NAMESPACE"
languages = []

[targets]
all = []

[ai]
rules_dir = ".agent/rules"
override_manifest = ".agent/overrides.yaml"
TOML
    echo "   Created leedevkit.toml"
fi

# Create .gitignore entries if needed
if [ -f .gitignore ]; then
    if ! grep -q '\.leedevkit/' .gitignore 2>/dev/null; then
        echo "" >> .gitignore
        echo "# DevKit (per-project install)" >> .gitignore
        echo '.leedevkit/' >> .gitignore
        echo 'leedevkit' >> .gitignore
    fi
else
    cat > .gitignore << 'GITIGNORE'
# DevKit (per-project install)
.leedevkit/
leedevkit
GITIGNORE
fi

echo ""
echo "✅ leedevkit $VERSION_TAG installed in .leedevkit/"
echo ""
echo "   Run:"
echo "     ./leedevkit doctor"
echo "     ./leedevkit test all"
echo ""
echo "   No global install needed. Everything is in .leedevkit/"
