#!/bin/bash
# leedevkit bootstrap — per-project install (no global)
# Usage: curl -fsSL https://raw.githubusercontent.com/vkaylee/leedevkit/main/bootstrap.sh | bash
#
# Downloads the devkit release and installs it into .leedevkit/ in the current
# directory. No global install, no PATH modification, no root permissions.

set -euo pipefail

REPO="vkaylee/leedevkit"
VERSION="${1:-latest}"
RELEASE_BASE_URL="${LEEDEVKIT_RELEASE_BASE_URL:-https://github.com/$REPO/releases}"

# Must be in a project directory (has .git or leedevkit.toml)
if [ ! -d .git ] && [ ! -f leedevkit.toml ]; then
    echo "⚠️  No .git or leedevkit.toml found in current directory."
    echo "   Run this from your project root, or create leedevkit.toml first."
    echo ""
    echo "   mkdir my-project && cd my-project"
    echo "   git init"
    echo "   curl -fsSL .../bootstrap.sh | bash"
    exit 1
fi

echo "🚀 Installing leedevkit into .leedevkit/ (per-project, no global)..."

# Determine version tag
if [ "$VERSION" = "latest" ]; then
    VERSION_TAG=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": "\(.*\)".*/\1/')
else
    VERSION_TAG="$VERSION"
fi

echo "   Version: $VERSION_TAG"

# Download release tarball
TMP_DIR=$(mktemp -d)
trap 'rm -rf $TMP_DIR' EXIT

# Strip "v" prefix for tarball name (v0.1.0 → leedevkit-0.1.0.tar.gz)
VER="${VERSION_TAG#v}"
TARBALL_URL="$RELEASE_BASE_URL/download/$VERSION_TAG/leedevkit-${VER}.tar.gz"
echo "   Downloading: $TARBALL_URL"

if command -v curl &>/dev/null; then
    curl -fsSL "$TARBALL_URL" -o "$TMP_DIR/leedevkit.tar.gz"
elif command -v wget &>/dev/null; then
    wget -q "$TARBALL_URL" -O "$TMP_DIR/leedevkit.tar.gz"
else
    echo "❌ Need curl or wget"
    exit 1
fi

# Extract and validate in temporary staging before replacing an existing install.
STAGE_DIR="$TMP_DIR/stage"
mkdir -p "$STAGE_DIR"
python3 - "$TMP_DIR/leedevkit.tar.gz" "$STAGE_DIR" <<'PY'
import sys
import tarfile
from pathlib import Path, PurePosixPath

archive_path = Path(sys.argv[1])
destination = Path(sys.argv[2]).resolve()
with tarfile.open(archive_path, "r:gz") as archive:
    members = archive.getmembers()
    for member in members:
        path = PurePosixPath(member.name)
        if path.is_absolute() or ".." in path.parts:
            raise SystemExit(f"Unsafe archive path: {member.name}")
        if not (member.isfile() or member.isdir() or member.issym() or member.islnk()):
            raise SystemExit(f"Unsupported archive member: {member.name}")
    archive.extractall(destination, members=members)
PY
EXTRACTED=$(find "$STAGE_DIR" -mindepth 1 -maxdepth 1 -type d -name 'leedevkit-*' -print -quit)
ENTRY_COUNT=$(find "$STAGE_DIR" -mindepth 1 -maxdepth 1 | wc -l)
if [ "$ENTRY_COUNT" -ne 1 ] || [ -z "$EXTRACTED" ]; then
    echo "❌ Unexpected tarball structure"
    exit 1
fi
if [ ! -f "$EXTRACTED/VERSION" ] || [ "$(tr -d '\r\n' < "$EXTRACTED/VERSION")" != "$VER" ]; then
    echo "❌ Release VERSION does not match $VER"
    exit 1
fi
for REQUIRED in bin/leedevkit scripts/_orchestrator.py scripts/_devkit_integrity.py; do
    if [ ! -f "$EXTRACTED/$REQUIRED" ]; then
        echo "❌ Release missing required file: $REQUIRED"
        exit 1
    fi
done
DEVKIT_HOME="$EXTRACTED" python3 "$EXTRACTED/scripts/_devkit_integrity.py" verify

BACKUP=""
if [ -e .leedevkit ]; then
    BACKUP="$TMP_DIR/previous-leedevkit"
    mv .leedevkit "$BACKUP"
fi
if ! mv "$EXTRACTED" .leedevkit; then
    if [ -n "$BACKUP" ] && [ -e "$BACKUP" ]; then
        mv "$BACKUP" .leedevkit
    fi
    echo "❌ Failed to activate release"
    exit 1
fi
if [ -n "$BACKUP" ]; then
    rm -rf "$BACKUP"
fi

# Ensure scripts are executable
chmod +x .leedevkit/scripts/*.py 2>/dev/null || true
chmod +x .leedevkit/scripts/*.sh 2>/dev/null || true
chmod +x .leedevkit/bin/* 2>/dev/null || true

# Create project-local wrapper (real script, not symlink)
cat > leedevkit << 'WRAPPER'
#!/bin/bash
# LeeDevKit — project-local wrapper (auto-generated by bootstrap)
exec "$(cd "$(dirname "$0")" && pwd)/.leedevkit/bin/leedevkit" "$@"
WRAPPER
chmod +x leedevkit

# Create leedevkit.toml if missing
if [ ! -f leedevkit.toml ]; then
    PROJECT_NAME="$(basename "$(pwd)")"
    PROJECT_NAMESPACE="$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')"
    cat > leedevkit.toml << TOML
[devkit]
version = "$VER"
install = "per-project"
source = "release"

[project]
name = "$PROJECT_NAME"
namespace = "$PROJECT_NAMESPACE"
languages = []

[targets]
all = []

[ai]
rules_dir = ".agent/rules"
override_manifest = ".agent/overrides.yaml"
TOML
    echo "   Created leedevkit.toml"
else
    python3 - "$VER" <<'PY'
import re
import sys
from pathlib import Path

path = Path("leedevkit.toml")
version = sys.argv[1]
content = path.read_text()
updated, count = re.subn(
    r'(\[devkit\][^\[]*?\bversion\s*=\s*)"[^"]*"',
    lambda match: f'{match.group(1)}"{version}"',
    content,
    count=1,
    flags=re.DOTALL,
)
if count == 0:
    raise SystemExit("❌ Existing leedevkit.toml has no [devkit] version entry")
path.write_text(updated)
PY
    echo "   Updated leedevkit.toml: version = \"$VER\""
fi

# Create .gitignore entries if needed
if [ -f .gitignore ]; then
    if ! grep -q '\.leedevkit/' .gitignore 2>/dev/null; then
        echo "" >> .gitignore
        echo "# DevKit (per-project install)" >> .gitignore
        echo '.leedevkit/' >> .gitignore
        echo 'leedevkit' >> .gitignore
    fi
else
    cat > .gitignore << 'GITIGNORE'
# DevKit (per-project install)
.leedevkit/
leedevkit
GITIGNORE
fi

echo ""
echo "✅ leedevkit $VERSION_TAG installed in .leedevkit/"
echo ""
echo "   Run:"
echo "     ./leedevkit doctor"
echo "     ./leedevkit test all"
echo ""
echo "   No global install needed. Everything is in .leedevkit/"
